// front_end/src/views/Signup.vue
<template>
  <el-card class="box-card">
    <div style="margin: 20px"/>
    <el-form
        label-position="top"
        label-width="300px"
        :model="formLabelAlign"
        style="max-width: 460px"
    >
      <!--      <el-form-item label="Staff Id">-->
      <el-form-item label="staff_id">
        <el-input v-model="formLabelAlign.staff_id" placeholder="Staff Id"/>
      </el-form-item>
      <el-form-item label="Username">
        <el-input v-model="formLabelAlign.username" placeholder="Username"/>
      </el-form-item>
      <el-form-item label="Phone Number">
        <el-input v-model="formLabelAlign.phone" placeholder="Phone Number"/>
      </el-form-item>
      <el-form-item label="Email">
        <el-input v-model="formLabelAlign.email" placeholder="Email"/>
      </el-form-item>
      <el-form-item label="Password">
        <el-input v-model="formLabelAlign.password" placeholder="Password"/>
      </el-form-item>
      <el-form-item label="Confirm Password">
        <el-input v-model="formLabelAlign.r_password" placeholder="Confirm Password"/>
      </el-form-item>
    </el-form>
    <el-button @click="stu_create">stu_create</el-button>
    <el-button @click="admin_create">admin_create</el-button>
    <el-button @click="()=>router.push('/')">Home</el-button>
  </el-card>
</template>


<script lang="ts" setup>
import {reactive, ref} from 'vue'
import {useRouter} from "vue-router";
import axios from "axios";

const router = useRouter()

const labelPosition = ref('left')

const formLabelAlign = reactive({
  // username: '',
  staff_id: '',
  username:'',
  phone: '',
  email: '',
  password: '',
  r_password: '',
})

function stu_create() {
  axios.post('base/api/user/signup/', {
    // axios.post('http://127.0.0.1:8000/api/user/signup/', {
    'username': formLabelAlign.username,
    'staff_id': formLabelAlign.staff_id,
    "phone": formLabelAlign.phone,
    "email": formLabelAlign.email,
    "password": formLabelAlign.password,
    'r_password': formLabelAlign.r_password,
    "is_admin": 'student'
  }).then(res => {
    console.log('res.data:', res.data);
    console.log('res.data.code:', res.data.code)
    if (res.data.code === 200) {
      //跳转到登录
      router.push("/signin")
      console.log("stu注册成功")
    }
    if (res.data.code === 500) {
      console.log('status: 500')
    }
    if (res.data.code === 201) {
      console.log('status: 201')
    }
  }).catch(err => {
    console.log(err.message)
  });
}

function admin_create() {
  axios.post('base/api/user/signup/', {
    // axios.post('http://127.0.0.1:8000/api/user/signup/', {
    'username': formLabelAlign.username,
    'staff_id': formLabelAlign.staff_id,
    "phone": formLabelAlign.phone,
    "email": formLabelAlign.email,
    "password": formLabelAlign.password,
    'r_password': formLabelAlign.r_password,
    "is_admin": 'admin'
  }).then(res => {
    console.log('res.data:', res.data);
    console.log('res.data.code:', res.data.code)
    if (res.data.code === 200) {
      //跳转到登录
      router.push("/signin")
      console.log("admin注册成功")
    }
    if (res.data.code === 500) {
      console.log('status: 500')
    }
    if (res.data.code === 201) {
      console.log('status: 201')
    }
  }).catch(err => {
    console.log(err.message)
  });
}

</script>

<style>

.box-card {
  width: 480px;
  margin: auto;
  display: flex;
  /*vertical-align: middle;*/
}
</style>

// srms_frontend/src/pages/Signup.tsx
import React from 'react';
import { Link, useNavigate } from 'react-router-dom'
import { LockOutlined, UserOutlined } from '@ant-design/icons';
import { Button, Checkbox, Form, Input, Col, Row, Card } from 'antd';
import { IdcardOutlined, PhoneOutlined, MailOutlined } from '@ant-design/icons';
import axios from 'axios';

const Signup: React.FC = () => {

  const navigator = useNavigate()


  const submit = (form: any) => {
    axios.post('base/api/user/signup/', {
      // axios.post('http://127.0.0.1:8000/api/user/signup/', {
      'username': form.username,
      'staff_id': form.staff_id,
      "phone": form.phone,
      "email": form.email,
      "password": form.password,
      'r_password': form.r_password,
      "is_admin": 'student'
    }).then(res => {
      console.log('res.data:', res.data);
      console.log('res.data.code:', res.data.code)
      if (res.data.code === 200) {
        //跳转到登录
        navigator('/signin')
        console.log("stu注册成功")
      }
      if (res.data.code === 500) {
        console.log('status: 500')
      }
      if (res.data.code === 201) {
        console.log('status: 201')
      }
    }).catch(err => {
      console.log(err.message)
    });

  }



  const onFinish = (values: any) => {
    submit(values)
  };

  return (
    <Row style={{ marginTop: "5%" }}>
      <Col span={6} offset={9}>
        <Card title="Sign Up" bordered={true} style={{ margin: "auto" }}>
          <Form
            name="normal_login"
            className="login-form"
            layout='vertical'
            initialValues={{ remember: true }}
            onFinish={onFinish}
          >
            <Form.Item
              name="staff_id"
              label="Staff ID"
              rules={[{ required: true, message: 'Please input your Staff ID!' }]}
            >
              <Input prefix={<IdcardOutlined />} placeholder="Staff ID" />
            </Form.Item>
            <Form.Item
              name="username"
              label="Username"
              rules={[{ required: true, message: 'Please input your Username!' }]}
            >
              <Input prefix={<UserOutlined className="site-form-item-icon" />} placeholder="Username" />
            </Form.Item>
            <Form.Item
              name="phone"
              label="Phone"
              rules={[{ required: true, message: 'Please input your Phone Number!' }]}
            >
              <Input prefix={<PhoneOutlined />} placeholder="Phone Number" />
            </Form.Item>
            <Form.Item
              name="email"
              label="Email"
              rules={[{ required: true, message: 'Please input your Email!' }]}
            >
              <Input prefix={<MailOutlined />} placeholder="Email" />
            </Form.Item>
            <Form.Item
              name="password"
              label="Password"
              rules={[{ required: true, message: 'Please input your Password!' }]}
            >
              <Input
                prefix={<LockOutlined className="site-form-item-icon" />}
                type="password"
                placeholder="Password"
              />
            </Form.Item>
            <Form.Item
              name="r_password"
              label="Confirm Password"
              rules={[{ required: true, message: 'Please confirm your Password!' }]}
            >
              <Input prefix={<LockOutlined className="site-form-item-icon" />}
                type="password"
                placeholder="Confirm Password" />
            </Form.Item>



            {/* <Form.Item>
              <Form.Item name="remember" valuePropName="checked" noStyle>
                <Checkbox>Remember me</Checkbox>
              </Form.Item>

              <a className="login-form-forgot" href="">
                Forgot password
              </a>
            </Form.Item> */}
            <Form.Item>
              <Button type="primary" htmlType="submit" className="login-form-button">
                Signup
              </Button>
              OR <Link to="/signin">Signin now!</Link>
            </Form.Item>
          </Form>
        </Card >
      </Col >
      <Col span={9}></Col>
    </Row >
  );
};

export default Signup;
